language: python
before_install:
  - wget -q http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b -p /home/travis/miniconda
  - export PATH=/home/travis/miniconda/bin:$PATH
  - conda update --yes --quiet conda
  - sudo apt-get install octave
  - git clone https://github.com/eeglabdevelopers/eeglab.git
install:
    - conda create -n testenv --yes pip python=2.7
    - source activate testenv
    - conda install --yes --quiet numpy=1.11 matplotlib=1.5 numexpr scipy=0.19
    - conda install --yes --quiet nose coverage
    - pip install flake8 check-manifest
    - pip install coverage coveralls
    - python setup.py install
script:
    - make
    - flake8 --count picard
    - cd examples/matlab_octave
    - octave plot_ica.m
    - octave plot_ica_whiten.m
    - octave plot_ica_pca.m
    - octave --eval "addpath '../../eeglab'; eeglab; plot_ica_eeglab"
    - cd ..//..
after_success:
  - bash <(curl -s https://codecov.io/bash)
